### ISSUE TITLE
Update for TinyMCE 5

### ISSUE THREAD

**Issue by kiogo** [uploadcare/uploadcare-tinymce#10]
Get the following error with tinymce 5:
Failed to initialize plugin: uploadcare Error: editor.addButton has been removed in tinymce 5x, use editor.ui.registry.addButton or editor.ui.registry.addToggleButton or editor.ui.registry.addSplitButton instead

**Comment by nd0ut** [comment]
@kiogo

We just added support for TinyMCE 5.x. 

Check it out please!

**Comment by kiogo** [comment]
Works, thanks. Could you also include the dist version in this repo please?
https://uploadcare.github.io/uploadcare-tinymce/dist/uploadcare.tinymce/plugin.js

**Comment by nd0ut** [comment]
@kiogo 
It's in the `release` branch
https://raw.githubusercontent.com/uploadcare/uploadcare-tinymce/release/plugin.js
