### ISSUE TITLE
Support for TinyMCE 6.0

### ISSUE THREAD

**Issue by dan-matthew** [uploadcare/uploadcare-tinymce#28]
Hi, 

Just curious to know if there are plans to support this plugin for TinyMCE 6.0?
If, so. Wondering, if any timeline is available?

Thanks

**Comment by nd0ut** [comment]
Hey @dan-matthew, 
I released a new version with support for TinyMCE 6.x - see [v4.0.1 release](https://github.com/uploadcare/uploadcare-tinymce/releases/tag/v4.0.1)

Note that you need to pass options in a slightly different way:

```js
tinymce.init({
  selector: '#editor',
  plugins: 'uploadcare',
  toolbar: 'uploadcare',
  external_plugins: {
    uploadcare: '/path/to/uploadcare/plugin.js',
  },
  uploadcare: {
    publicKey: 'YOUR_PUBLIC_KEY',
    /* when handling images, you can resize them on a client to save bandwidth */
    imageShrink: '500x375',
    /* allow multi-file uploads */
    multiple: true,
    multipleMax: 3,
    /* set crop options when handling images */
    crop: '1:1,4:3',
    /* feel free to add more options here */
  }
})
```

**Comment by dan-matthew** [comment]
Thanks a lot for releasing support for TinyMCE 6.x @nd0ut
