### ISSUE TITLE
Edit previously uploaded images

### ISSUE THREAD

**Issue by dunnbro** [uploadcare/uploadcare-tinymce#8]
Hello, I'm interested in finding a way to re-edit a file that has already been uploaded with the tinyMCE plugin. That is, if I click on an image in tinyMCE that was previously uploaded using the plugin, I would like to be able to bring up the uploadcare dialog again to adjust the cropping, for example. 

Is there a possibility of adding this functionality? Or could you point me in the right direction as to how I might implement this feature? 

Thank you.

**Comment by dmitry-mukhin** [comment]
you can add an [effects tab](https://uploadcare.com/features/effects_tab/), for example.
the main question is, if the element html is editable.
@Zmoki what do you think?

**Comment by Zmoki** [comment]
@dunnbro hi! Sorry for the delay, I was sick.

I added PR with the editing of uploaded images and files. You can check it locally, just clone repo, check out to the `edit-uploaded-content` branch, run `npm install`, after run `npm run dev` and `npm start` and you‘ll see a demo in your browser and can play with it. Or use the plugin from the archive 
[uploadcare.tinymce.zip](https://github.com/uploadcare/uploadcare-tinymce/files/2869328/uploadcare.tinymce.zip) (not for production).


If it right way to re-edit for you, I can publish a new version of the plugin soon.

**Comment by dunnbro** [comment]
@Zmoki Yes, this is precisely the functionality I was looking for. This is great, thanks a lot!
